### ISSUE TITLE
setup fails on TASK [auth-server : enable persona-auth server service]

### ISSUE THREAD

**Issue by mattStorer** [smart-on-fhir/installer#10]
hey again!  first lemme say I really appreciate all your efforts to resolve these bugs!  thank you very much!

that said -

I encountered an error following the instructions for **Building SMART-on-FHIR on fresh Ubuntu 16.04 machine (without Vagrant)** at https://github.com/smart-on-fhir/installer. The error occurs in _TASK : [auth-server : enable persona-auth server service]_ with error _"Created symlink from /etc/systemd/system/multi-user.target.wants/persona-auth-server.service to /etc/systemd/system/persona-auth-server.service.\nFailed to execute operation: Connection timed out"_.

error screenshot:
![installer-error-enable-persona-auth-server-service](https://cloud.githubusercontent.com/assets/979938/24563617/f26ec6e4-1603-11e7-8bbf-2dc18bf56547.jpg)

My environment is:
- VirtualBox 5.1.14r112924
- Ubuntu Linux VM at version 16.04.2-server-amd64

**Comment by amyballard** [comment]
Hey Matt,
Travis usually jumps in on these installer issues. He's out this week. I'll see if I can figure out what's going on.

**Comment by mattStorer** [comment]
Thanks Amy!  Yeah, the only errors I seem to be encountering these days are timeout issues, whether on this task or on the baseline-snapshot task (usually it's the baseline-snapshot task).  _once_ I was able to complete the installation without errors, so it seems like this is not so much a structural issue as it is one of a race condition.

Perhaps increasing timeouts to something much larger than what it currently uses is all that's needed?  Throwing darts here.  Let me know if there's anything I can do to help!

**Comment by travistcummings** [comment]
Hi Matt, is this issue still causing you problems?

**Comment by mattStorer** [comment]
It's hard to say.  I've tried the install several times, and only got it to complete once.  The other times (probably 5 or 6 in all) I wind up mostly getting a timeout error on the baseline-snapshot task (https://github.com/smart-on-fhir/installer/issues/9), but one time I got this error.  So, it could be that the next time I run the install, it won't fail on this task - but that doesn't mean it's fixed, right?  Race condition bugs are the _best_!  haha /sarcasm 

seriously though thanks for your help with these!

**Comment by dbaker007** [comment]
Not sure if this is related... but my install just hangs trying to verify the auth server.

TASK [auth : stop auth server] *************************************************
ok: [localhost]

TASK [auth : restart auth server] **********************************************
changed: [localhost]

TASK [auth : configure nginx (auth server)] ************************************
ok: [localhost]

TASK [auth : verify auth-server is available] **********************************

**Comment by travistcummings** [comment]
Hi, can you please try out the 1.1.0 release?  It uses personas in a different manor.
