### ISSUE TITLE
Preserve LF on Windows

### ISSUE THREAD

**Issue by mrinnetmaki** [smart-on-fhir/installer#11]
In addition to managing line feeds when checking code in and out from the repository, it's necessary to preserve the *nix style line feeds when editing the files in Windows environment, so the scripts run well in the virtual machine.

Currently that's not the case. When you edit files on your Windows machine, they are saved with Windows style line endings.

**Comment by jmandel** [comment]
Is there a technical fix for this, or just an issue we need to document?

**Comment by mrinnetmaki** [comment]
There is a fix. Submitted a PR.
