### ISSUE TITLE
Sandbox Manager - cannot create new user, PWM app unavailable

### ISSUE THREAD

**Issue by mattStorer** [smart-on-fhir/installer#11]
Good afternoon.  I've created a local installation of the SMART on FHIR Installer, which I am now trying to configure.  _(note that timeout errors continue to plague repeated attempts to install the Installer on fresh Ubuntu systems, see https://github.com/smart-on-fhir/installer/issues/9 and https://github.com/smart-on-fhir/installer/issues/10 for details)_

With my one successful setup, I'm trying to make some headway into setting up and configuring the sandbox.  However, I appear to be unable to create a new user account, due to the PWM application being unavailable.

![sandbox-manager-pwm-app-unavailable](https://cloud.githubusercontent.com/assets/979938/24775139/7250c4b8-1ad0-11e7-8f8e-6c0a2516bec9.jpg)

Additionally, there appears to be a minor-if-frustrating issue with the system presuming "localhost" when it should be using the external-facing IP address (perhaps it's hardcoded somewhere?) on the auth/login screen:

![sandbox-manager-create-account-wrong-domain](https://cloud.githubusercontent.com/assets/979938/24775171/8fa97d98-1ad0-11e7-8e68-64c4a45271db.jpg)

My environment is a VirtualBox VM running Ubuntu 16.04.2 server (64-bit) on a Windows 7 host.

**How can I get the PWM application running?**

Please assist!  Thanks!

**Comment by amyballard** [comment]
I'll take a look.

**Comment by amyballard** [comment]
I ran the install an am seeing the same thing. It's like the PWM server didn't start. I tried a few things, but I'm going to have to wait until Travis is back on Monday to look at it. You probably know this, but you can login with demo/demo or admin/password in the mean time.

**Comment by travistcummings** [comment]
Hi Matt, 

Adding users is beyond the scope of the personal installer because the intention is to allow you to have a completely working smart of fhir stack. This includes a Smart-protected fhir server, an oauth server, and a smart launch simulator. That admin account allows managing the oauth clients and the demo account represents an unprivileged user account. Also the sandbox manager "personas" allow creating synthetic patient and practitioner login accounts.

We actually had removed the link to create new accounts for the personal installer but it has appeared again somehow!

I'll take a look at the timeout issues when I'm back in town on Monday.

Thank you for your feedback! I'm working on a more reliable installer topology too.

Travis

**Comment by mattStorer** [comment]
Hey Travis, Amy -

Thanks for your attention to these issues, and for your excellent communication!  It's much appreciated.

**Amy** : thanks for that login info, I was not actually aware of those user accounts.  Are they documented somewhere that I evidently missed?  I'm glad to hear the error is reproducible!

**Travis** : okay, so let me see if I understand what you're saying correctly -

1. the Installer is designed to create _"a Smart-protected fhir server, an oauth server, and a smart launch simulator"_ - meaning that upon successful completion of an Installer installation, these systems and services should be running and fully operational; and
2. users shouldn't be able to create their own accounts, because all user administration should be handled by the admin account.

Correct?

On a related note, ultimately we here are interested in standing up a service to easily test SMART on FHIR apps (where people can register their apps and make them available for other people to use), which the Sandbox is going to be great for I think.  However, I think we would ultimately also like to have such a launcher operate against real EHR data.  Can the Sandbox be configured to work against real data?  Or barring that, is there a better tool you're aware of to do this?

Also, is there documentation available for how to use and configure the Installer / Sandbox?

I know I just asked a lot of questions, no real rush getting back, but I would definitely appreciate your input on this at your earliest convenience!

Thanks again -

Matt

**Comment by amyballard** [comment]
Matt, 
The user accounts are mentioned in a paragraph of the Github doc:
"The authorization server uses the OpenLDAP server running on the virtual machine. The two sample accounts are demo/demo and admin/password by default. You should change these for production environments. You can connect to the LDAP server on localhost:10389."

**Comment by travistcummings** [comment]
Hi Matt,

The purpose of the installer is to let users create a SMART on FHIR "reference" platform using open-source libraries.

Key functions a user could gain from this are:

- a smart-launch simulator for developing smart-apps (the apps can be production quality)
- a smart-protected reference FHIR server that is open-source
- a smart-aware reference Oauth2 server that is open-source

There no intention for the installer to create a platform that is ready for production, or contain real patient data, or support a real user database.  The platform does have an ApacheDS server that could be used to host user accounts (it does on the smart sandbox system).  The admin account allows direct login to the auth server with admin access and the demo account represents an practitioner login for launching apps.

The SMART sandbox is available as a deployment of the smart platform for shared access with test data.

Another sandbox, the HSPC sandbox allows for creating free personal fhir servers with more development tools.

For real EHR data, the EHR providers have their own SMART-enabled launch sandboxes that are pipelines into their respective stores and real-world hospital systems.

Travis
