### ISSUE TITLE
undefined mock_* ansible variables

### ISSUE THREAD

**Issue by myungchoi** [smart-on-fhir/installer#12]
Hi, the ansible script is failing due to the undefined ansible variables. Those are mostly mock_api_* variables. For example, mock_api_dstu2_server_smart_sandbox_url is not defined. I tried to set this variable in the global_settings. But, then it leads to another undefined variable such as mock_api_dstu2_server_host, port, context, etc.

I am trying to install this on Ubuntu 16.04 LTS and following installation instruction for Ubuntu installation.

Would you check on your side and let us know how these variables need to be defined?

**Comment by travistcummings** [comment]
Hi, I've merged the 1.0 branch into master and this issue is fixed.  Please try again.

Thanks,
Travis
