### ISSUE TITLE
installer_user is undefined

### ISSUE THREAD

**Issue by cnmaier** [smart-on-fhir/installer#15]
I tried to use your installer on a fresh Ubuntu 16.04 amd64 server edition and changed the variables in inventory_example.yml as well as in custom_settings.yml according to the readme.

However, it seems that the variables are not recognized:

No config file found; using defaults
Loaded callback default of type stdout, v2.0

PLAYBOOK: site.yml *************************************************************
8 plays in site.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1497873416.75-68853503152424 `" && echo ansible-tmp-1497873416.75-68853503152424="` echo $HOME/.ansible/tmp/ansible-tmp-1497873416.75-68853503152424 `" ) && sleep 0'
<localhost> PUT /tmp/tmp3eqdjz TO /home/omop/.ansible/tmp/ansible-tmp-1497873416.75-68853503152424/setup
<localhost> EXEC /bin/sh -c 'LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8 /usr/bin/python /home/omop/.ansible/tmp/ansible-tmp-1497873416.75-68853503152424/setup; rm -rf "/home/omop/.ansible/tmp/ansible-tmp-1497873416.75-68853503152424/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [linux : check custom certificate preconditions] **************************
task path: /home/omop/installer/provisioning/installer/provisioning/roles/linux/tasks/main.yml:2
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [linux : include] *********************************************************
task path: /home/omop/installer/provisioning/installer/provisioning/roles/linux/tasks/main.yml:7
included: /home/omop/installer/provisioning/installer/provisioning/roles/linux/tasks/initialize.yml for localhost

TASK [linux : installer profile] ***********************************************
task path: /home/omop/installer/provisioning/installer/provisioning/roles/linux/tasks/initialize.yml:2
**fatal: [localhost]: FAILED! => {"failed": true, "msg": "/home/{{installer_user}}: 'installer_user' is undefined"}**
        to retry, use: --limit @site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

**Comment by vsocrates** [comment]
I'm having the same problem above. I added an /etc/ansible/hosts file and added the line: ```localhost ansible_connection=local```. While I'm having other issues, the above went away.

**Comment by yinxie** [comment]
The steps just don't work, I could fix the installer_user using extra-vars, but there are many more undefined vars coming. Are these step have been tested at all?

**Comment by cnmaier** [comment]
I have also made it to progress further with extra vars. I am currently using the following command:

`sudo ansible-playbook -e 'installer_user=omop' -e 'services_host=localhost' -e 'use_secure_http=true' -e 'use_custom_ssl_certificates=false' -e 'certificate_crt_filename=self-signed-certificate.crt' -e 'certificate_key_filename=self-signed-certificate.key' -e 'keystore_password=omop' -e 'hspc_platform_jwt_key=omop' -e 'aws_output_format=json' -e 'aws_region=omop' -e 'aws_access_key_id=omop' -e 'aws_secret_access_key=omop' -e 'aws_ec2_volume_id=omop' -e 'mysql_host=localhost' -e 'mysql_password=password' -e 'enable_pwm=false' -e 'pwm_server_external_host={{services_host}}' -e 'pwm_server_external_port=9092' -e 'apacheds_server_external_host={{services_host}}' -e 'apacheds_server_system_admin_password=secret' -e 'apacheds_server_sandbox_admin_password=password' -e 'apacheds_server_installer_enabled=true' -e 'auth_server_external_host={{services_host}}' -e 'auth_server_external_port=9060' -e 'auth_server_initial_memory=32M' -e 'auth_server_max_memory=128M' -e 'auth_server_newUserUrl=' -e 'auth_server_forgotPasswordUrl=' -e 'auth_server_admin_password=password' -e 'auth_mysql_reset_database=true' -e 'api_server_oauth2_clientId=hspc_resource_server' -e 'api_server_oauth2_clientSecret=secret' -e 'api_dstu2_server_external_host={{services_host}}' -e 'api_dstu2_server_external_port=9071' -e 'api_dstu2_server_initial_memory=128M' -e 'api_dstu2_server_max_memory=256M' -e 'api_dstu2_mysql_reset_database=true' -e 'api_dstu2_sample_patients_limit=20' -e 'mock_api_dstu2_server_external_host={{services_host}}' -e 'mock_api_dstu2_server_external_port=9271' -e 'mock_api_dstu2_server_initial_memory=128M' -e 'mock_api_dstu2_server_max_memory=256M' -e 'api_stu3_server_external_host={{services_host}}' -e 'api_stu3_server_external_port=9074' -e 'api_stu3_server_initial_memory=128M' -e 'api_stu3_server_max_memory=256M' -e 'api_stu3_mysql_reset_database=true' -e 'mock_api_stu3_server_external_host={{services_host}}' -e 'mock_api_stu3_server_external_port=9274' -e 'mock_api_stu3_server_initial_memory=128M' -e 'mock_api_stu3_server_max_memory=256M' -e 'sandman_mysql_reset_database=true' -e 'enable_backup_restore_jobs=false' -e 'enable_aws_snapshot=false' -e 'enable_api_sample_data=true' -e 'enable_mock_endpoints=false' -e 'messaging_server_external_host=localhost' -e 'messaging_server_external_port=8091' -e 'messaging_server_initial_memory=1M' -e 'messaging_server_max_memory=32M' -e 'messaging_profiles=test' -e 'sandman_server_external_host={{services_host}}' -e 'sandman_server_external_port=9080' -e 'sandman_server_initial_memory=16M' -e 'sandman_server_max_memory=128M' -e 'sandman_server_send_email=false' -e 'sandbox_server_admin_access_client_secret=omop' -e 'apps_server_external_host={{services_host}}' -e 'apps_server_external_port=9093' -e 'patient_picker_server_external_host={{apps_server_external_host}}' -e 'patient_picker_server_external_port={{apps_server_external_port}}' -e 'custom_ssl_certificates_path=/home/omop/' -c local -i 'localhost,' -vvvv site.yml`

This fixes problems with the undefined vars at least, however, there are many more problems coming up.

**Comment by yinxie** [comment]
It'd be nice to get some traction on this issue. This is blocking.

**Comment by vsocrates** [comment]
While I'm not a contributor, I did have this issue. I'm running on a t2.large EC2 instance, from fresh install. Reading ansible documentation led me to creating a directory at `/etc/ansible/host_vars` and added a file called `localhost` there with all the variables from the `installer/provisioning/inventory_example.yml` file (with my own settings). 

This will only work if you have the `/etc/ansible/hosts` file with the line: `localhost ansible_connection=local` I mentioned above.

From my understanding, this is setting the default connection as a 'local' connection for ansible, and the variables required to run the playbook come from the `host_vars` folder due to ansible default config. I think the docs need to be changed to make this clearer? Hopefully this is helpful to someone! 

source: [http://docs.ansible.com/ansible/intro_inventory.html](url)

**Comment by yinxie** [comment]
I've created /etc/ansible/hosts and have "localhost ansible_connection=local" in the file. The problem still persists.

**Comment by vsocrates** [comment]
Did you add the variables to a `host_vars` dir like I mentioned above?

**Comment by yinxie** [comment]
Yes, did that. the error still occurs.

**Comment by travistcummings** [comment]
Hi these issues should be fixed now.  Please refer to the updated instructions concerning native install and inventories.
