### ISSUE TITLE
Unexpected error when accessing exploded file: [Errno 2] File or directory not found: '/home/fhir/apacheds-2.0.0-M23'

### ISSUE THREAD

**Issue by cnmaier** [smart-on-fhir/installer#16]
Besides the problem with the undefined vars, which has been fixed in #15 , I get this error:

TASK [setup] *******************************************************************
ok: [localhost]

TASK [apacheds : remove existing apacheds installation] ************************
ok: [localhost]

TASK [apacheds : extract configured apacheds] **********************************
fatal: [localhost]: FAILED! => **{"changed": false, "failed": true, "msg": "Unexpected error when accessing exploded file: [Errno 2] File or directory not found: '/home/fhir/apacheds-2.0.0-M23'"}**

The apacheds tarball is downloaded to `installer/provisioning/roles/apacheds/files/apacheds-2.0.0-M23-configured.tar`, however, apparently not copied to `/home/fhir/`.

The system is a fresh Ubuntu 16.04 amd64 server edition.

**Comment by cnmaier** [comment]
Seems to be a problem with ansible. I found a fix [here](https://github.com/ansible/ansible-modules-core/issues/3706#issuecomment-234281145).

Add the `environment` parameters to the task `extract configured apacheds` in `installer/provisioning/roles/apacheds/tasks/main.yml`:


name: "extract configured apacheds"
  when: apacheds_server_installer_enabled
  become_user: "{{hosting_username}}"
  unarchive: src="apacheds-2.0.0-M23-configured.tar" dest="{{hosting_user_home}}"
  **environment:
         LANG: C
         LC_ALL: C
         LC_MESSAGES: C**

**Comment by travistcummings** [comment]
Closing old issues.  The installer runs successfully.  Please let me know if there are still problems with this.
