### ISSUE TITLE
"Choose a Patient" screen hangs after "Next"

### ISSUE THREAD

**Issue by gbtorrance** [smart-on-fhir/installer#17]
After #15 was closed, I retried the install process. It mostly worked. There were a few tasks that failed, but the overall process appears to have succeed. (Many of the Ansible tasks scrolled off of the terminal buffer, but a few of the errors are shown below.)

The main reason for this issue, though, is that the Sandbox hangs on the "Choose a Patient" screen after clicking "Next" on page 1. Is this an issue with my setup, or with the Sandbox itself?

Thanks,
Greg

![20170705_smartsandboxchooseapatientnexterror](https://user-images.githubusercontent.com/16735709/27863894-2c7fd0ac-615a-11e7-940c-395900901c52.PNG)

< TASK [apps : check out the tag v0.1.3] >
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "git checkout  tags/v0.1.3", "delta": "0:00:00.003137", "end": "2017-07-05 07:53:04.778550", "failed": true, "rc": 1, "start": "2017-07-05 07:53:04.775413", "stderr": "error: pathspec 'tags/v0.1.3' did not match any file(s) known to git.", "stdout": "", "stdout_lines": [], "warnings": ["Consider using git module rather than running git"]}
...ignoring

< TASK [apps : stop apps] >
 -------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "systemd could not find the requested service \"'apps'\": "}
...ignoring

**Comment by travistcummings** [comment]
Resolving these old issues.  This was most likely due to a problem with the patient picker service not being deployed properly.

Can you please try again if you are still interested?
