### ISSUE TITLE
Task [Common: Set Private Key Permissions] variable still evaluates and fails even when the condition does not pass

### ISSUE THREAD

**Issue by MikeRileyGTRI** [smart-on-fhir/installer#2]
I'm following the standard build process as detailed on the README.

There are some tasks related to ssl that I am not enabling. Even still, a variable that did not get initialized correctly still gets evaluated and crashes the standard smart-on-fhir,yml build.

I was able to get around this by simply commenting out  the offending task.

Exert from the tail of my ansible run.

TASK [common : create ssl certificates directory] ******************************
task path: /tmp/src/OAuth_Server/provisioning/roles/common/tasks/main.yml:73
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}
/
TASK [common : copy custom ssl certificates] ***********************************
task path: /tmp/src/OAuth_Server/provisioning/roles/common/tasks/main.yml:78
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}

TASK [common : add www-data user to ssl-cert group] ****************************
task path: /tmp/src/OAuth_Server/provisioning/roles/common/tasks/main.yml:86
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}

TASK [common : list private key files] *****************************************
task path: /tmp/src/OAuth_Server/provisioning/roles/common/tasks/main.yml:91
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}

TASK [common : set private key permissions] ************************************
task path: /tmp/src/OAuth_Server/provisioning/roles/common/tasks/main.yml:97
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "'dict object' has no attribute 'stdout_lines'"
}
        to retry, use: --limit @/*****/provisioning/smart-on-fhir.retry

**Comment by nschwertner** [comment]
Interesting. Thank you for reporting. Are you building using Vagrant? Which version of Ansible are you trying this against?

**Comment by MikeRileyGTRI** [comment]
Thanks for the timely response. GTRI is using this for a FHIR environment.

I am not building with vagrant, I am building on a virtual Ubuntu 16.04 server machine. So almost identical to the machine Vagrant wants to use. I am building with ansible version 2.2.0. Although months ago I had built this project using ansible version 1.8.2. That was when the default entry yaml was called smart-on-fhir-servers.yml

**Comment by travistcummings** [comment]
Hi Mike,

Am I to understand that you are following the readme section:

Building SMART-on-FHIR on fresh Ubuntu 16.04 machine (without Vagrant)

Can you provide more details about your install so I can replicated it?
What is your target platform?  Am I correct that you are doing a local
install?  What values have you provided in custom_settings.yml?

Thanks,
Travis

On Wed, Dec 7, 2016 at 9:05 AM MikeRileyGTRI <notifications@github.com>
wrote:

Thanks for the timely response. GTRI is using this for a FHIR environment.

I am not building with vagrant. I am building with ansible version 2.2.0.
Although months ago I had built this project using ansible version 1.8.2.
That was when the default entry yaml was called smart-on-fhir-servers.yml

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/smart-on-fhir/installer/issues/2#issuecomment-265488694>,
or mute the thread

**Comment by MikeRileyGTRI** [comment]
My build process was very simple.

sudo apt-get install ansible
git clone github.com/smart-oh-fhir/installer.git
cd installer
ansible-playbook -c local -i 'localhost,' -vvvv smart-on-fhir.yaml

For this particular example, everything is on one machine (localhost). No changes to the custom defaults. No extra configuration.

The target machine OS is a ubuntu_server_16.04

I am using a minor version increase on ansible: 2.2 instead of 2.1. I can try another run with the correct ansible version. I have written some of my own ansible scripts, but I am ignorant with how the minor updates change ansible.

**Comment by travistcummings** [comment]
Hi Mike,

I can replicate your error if I use Ansible 2.2.  Is it possible for you to
use Ansible 2.1?  I'm not sure the timeframe for migrating to Ansible 2.2.

Thanks,
Travis

**Comment by MikeRileyGTRI** [comment]
Sure thing Travis. I'm going to try and get that run done today and get you guys the results.

**Comment by MikeRileyGTRI** [comment]
I ran the  same script with ansible 2.1 and received the same result. I can attach a log file if you wish.

**Comment by travistcummings** [comment]
Could you please?  I also ran it with Ansible 2.1 and it was successful,
then ran it with Ansible 2.2 and received your error.

**Comment by MikeRileyGTRI** [comment]
Travis there seems to be a weird interaction between ansible-playbook, pip, and my bin folder. Ansible playbook keeps reverting to the 2.2.0 version that I installed with pip, rather than the 2.1 version I had to install using ubuntu's apt. Removing 2.2 with pip and installing 2.1 with pip fixed my issue here.

The build runs with version 2.1 but it effectively skips the task as well. Here's the message on the task


TASK [common : set private key permissions] ************************************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'stdout_lines'.
This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by travistcummings** [comment]
I've just checked in a fix for the 'stdout_lines' error relating to private
keys.

Can you let me know if that fixes your problem?

Thanks,
Travis

**Comment by nschwertner** [comment]
Assuming this is resolved, so closing the ticket

**Comment by MikeRileyGTRI** [comment]
Ah sorry, this is resolved.

**Comment by paulorades** [comment]
Hi, I'm doing SMART deploy on UBUNTU 14 following the steps of Building SMART-on-FHIR on fresh Ubuntu 14.04 machine (without Vagrant)

apt-get update
apt-get install curl git python-pycurl python-pip python-yaml python-paramiko python-jinja2
pip install ansible == 1.6
git clone https://github.com/smart-on-fhir/smart-on-fhir-installer
cd smart-on-fhir-installer / provisioning

So far so good.

When I run

ansible-playbook -c local -i 'localhost,' -vvvv smart-on-fhir-servers.yml

This error occurs:

ERROR: stat is not a legal parameter in an Ansible task or handler


Can you help, please?

Thank you

**Comment by MikeRileyGTRI** [comment]
Hi Paulo. Thanks for all the information and  update. I will look into it.


I believe the ansible version is very finnicky. Can you run ansible --version for me?


________________________________

**Comment by paulorades** [comment]
Hi Mike. Tks to response.

I started a new installation (Windows 10 + Virtualbox + Ubuntu Server 16.04) and ran deploy with ansible 2.1.0.

Apparently everything ran correctly but at the end I get error according to the attached screen ....

![erro-ansible-2 1 0](https://user-images.githubusercontent.com/10406190/31100724-f66ee5ce-a7a0-11e7-8f70-bc1a5bbfabe6.png)

**Comment by MikeRileyGTRI** [comment]
It looks  like  you can't see the link at download.oracle.com.


What step did this error happen on?

What role were you running?


I would also try and curl download.oracle.com. I got an oracle sso page.


It looks like ansible is trying to pull down jdk7, not the now standard jdk8. In order to get jdk7, you need some oracle support now. AKA not available. I'm not super certain why ansible wants to pull jdk7 instead of jdk8. I've specified default-jdk-latest as the version in ansible. Perhaps your apt repository doesn't have a jdk8? I would start looking at your apt-cache list and making sure jdk8 is supported.


________________________________

**Comment by paulorades** [comment]
Hi, Mike.

The error too occurs when I ran: (note: ansible is 2.1):
ansible-playbook -c local -i 'localhost,' -vvvv smart-on-fhir-servers.yml

![versoes-java-ansible](https://user-images.githubusercontent.com/10406190/31107518-558c00f0-a7c9-11e7-974b-a69a350ad604.png)

The role file is default - vanilla install
The account I use is not root, in Ubuntu I use sudo to execute administrative commands.


I followed your suggestion and manually updated oracle to JDK8 and ran again:
ansible-playbook -c local -i 'localhost,' -vvvv smart-on-fhir-servers.yml

But now it generates the error of SSL_ST_INIT ...


![erro-smart-ssl](https://user-images.githubusercontent.com/10406190/31107570-bae2272c-a7c9-11e7-8286-fbe2824b3bdd.png)



See screenshots with versions and error after ansible ...
