### ISSUE TITLE
In a fresh install Timeout when waiting for localhost:8080

### ISSUE THREAD

**Issue by miscaminatas** [smart-on-fhir/installer#20]
Hi!
From Argentina...
Smart on FHIR Rocks! Thank you!

I see a few problems at fresh install
1.- provisioning/roles/sandman/tasks/artifact.yml
Line 57 "apps.html" file not found! - Stop Install with Error!

2.- provisioning/roles/sandman/tasks/artifact.yml
Line 79 "services.js" file not found! - Stop Install with Error!

In the End.... "msg"  "msg": "Timeout when waiting for localhost:8080"}
Stop Install with error! This files just changed (Sep/7/2017 aprox 19 hs before)

That all folks for now!
May I help you? 

Apologies for my English!!!
mail miscaminatas@gmail.com
I´m Cardiologist and Love mHealth - Telemedicine - SmartOnFhir - EHR -

**Comment by travistcummings** [comment]
Hi,

Can you please try again with a fresh copy from Master?  Quite a few changes have been released in the last month.

Thanks,
Travis
