### ISSUE TITLE
Newer versions of Ansible, Virtualbox and Vagrant supported?

### ISSUE THREAD

**Issue by Joe-cvp** [smart-on-fhir/installer#21]
- Installed the latest Virtualbox, Vagrant and Ansible
- Followed the instructions in the ReadMe
-  Got about 5 minutes into the vagrant up command and I get "can't find apps.html"

Are the latest versions of tools supported?

**Comment by miscaminatas** [comment]
I found some error installation
Server Ubuntu 16.04

provisioning/roles/sandman/tasks/artifact.yml
Line 57 "apps.html" file not found! 

Any idea?

Alejandro

**Comment by Joe-cvp** [comment]
It looks like apps.html and services.js are present on the develop branch.  I copied those two files and was able to start the VM, but with errors.  I wonder if the develop branch should be used instead of master?

**Comment by travistcummings** [comment]
The versions listed in README.md are the supported versions.  I tried an Ansible 2.4.0 installation and can't remember the specific error, but Ansible is famous for not being backward compatible.  

The release versions are available on Master.  Quite a bit has changed recently so it might be worth starting with a fresh codebase and following the steps in the README.md.  Make sure to execute the new ansible_galaxy task:

ansible-galaxy install -r roles/requirements.yml -p ./roles/ --force

Travis
