### ISSUE TITLE
'Take' snapshot task fails with "timed out" error

### ISSUE THREAD

**Issue by ris58h** [smart-on-fhir/installer#24]
`TASK [api : baseline snapshot] *************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Connection failure: timed out", "redirected": false, "status": -1, "url": "http://my-vm-name:9071/smartdstu2/sandbox/snapshot/default"}
        to retry, use: --limit @/home/administrator/installer/site.retry`

Taking a snapshot takes about 77 seconds for my environment, so I had to add a timeout option (default is 30 as I know) to roles/api/tasks/snapshot-command.yml.

**Comment by travistcummings** [comment]
I've increased the timeout to 90 seconds.  Thanks!
