### ISSUE TITLE
Installer Fails at Sandbox Manager Role

### ISSUE THREAD

**Issue by ghost** [smart-on-fhir/installer#26]
Some recent updates seemed to have lead to the installer no longer working correctly.  At first, I was getting an error stating that the variable `sandman_project_version` was not set correctly. After setting the variable I started getting the following error:

```
TASK [sandbox-manager-role : check out project] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin https://bitbucket.org/hspconsortium/sandman.git /home/fhir/sandman/project", "failed": true, "msg": "fatal: destination path '/home/fhir/sandman/project' already exists and is not an empty directory.", "rc": 128, "stderr": "fatal: destination path '/home/fhir/sandman/project' already exists and is not an empty directory.\n", "stderr_lines": ["fatal: destination path '/home/fhir/sandman/project' already exists and is not an empty directory."], "stdout": "", "stdout_lines": []}
```

It appears a recent change to the sandbox manager role when switching from a maven repository to a git repository lead to the error.  Any help in resolving this issue would be greatly appreciated.

**Comment by travistcummings** [comment]
Hi, the correct property is called "sandman_server_project_version".  It should exist in your environment file similar to the local.yml:

sandman_server_project_version: "2.6.6"

The Sandbox Manager has changed from a Java WAR to a NodeJS project, and is no longer an Ansible Galaxy role.
