### ISSUE TITLE
Issue when Building SMART-on-FHIR on fresh Ubuntu 16.04 machine (without Vagrant): LDAP role not found!

### ISSUE THREAD

**Issue by mohan-gliimpse** [smart-on-fhir/installer#3]
Hello,

I'm trying to follow the steps outlined under heading: **Building SMART-on-FHIR on fresh Ubuntu 16.04 machine (without Vagrant)**.

When I run this command -- _sudo ansible-playbook  -c local -i 'localhost,' -vvvv smart-on-fhir.yml_ -- I am getting this error:

```
No config file found; using defaults
ERROR! the role 'ldap' was not found in /home/ubuntu/installer/provisioning/roles:/home/ubuntu/installer/provisioning:/etc/ansible/roles

The error appears to have been in '/home/ubuntu/installer/provisioning/smart-on-fhir.yml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - common
    - ldap
      ^ here
```

Can you tell me how to get around this issue?  It seems that the ldap role does not exists.

**Comment by nschwertner** [comment]
Seems wrong indeed. @travistcummings recently did some restructuring of the installer roles. Hopefully he will be able to help

**Comment by mohan-gliimpse** [comment]
Thank you.  

I'm hoping that this could be resolved relatively quickly.  Also, I was wondering if there is documentation about which exact endpoints to hit for OAuth to ultimately retrieve tokens and how to hit the API with those tokens.

Thanks in advance.

**Comment by travistcummings** [comment]
Hi,

The new playbook file is "site.yml".  You can see the new command on the README.md:
```
sudo ansible-playbook -c local -i 'localhost,' -vvvv site.yml
```
README.md also contains a listing of the applications that will be running on each port.  To complete the SMART launch flow, you will use the Sandbox Manager to register and launch your application.

Thank you, 
Travis
