### ISSUE TITLE
Unicode decoder error

### ISSUE THREAD

**Issue by tse-tamir** [smart-on-fhir/installer#4]
I am trying to build the FHIR on my fresh ubuntu 14.04 virtual machine and I got the following error when i execute ansible command from terminal. Can you please help me to solve this problem?

![untitled](https://cloud.githubusercontent.com/assets/8093401/14884781/7de8cb46-0d47-11e6-8f8a-f4abb53801c5.png)

**Comment by jmandel** [comment]
Looks like its may be a similar situation to https://www.blue-bag.com/blog/yaml-death-non-breaking-spaces -- can you clarify whether you have edited  any of the yaml configuration files by hand? 

@nschwertner have you seen this behavior before?

**Comment by tse-tamir** [comment]
Thanks for answering.
I did not change anything in yaml configuration files.

**Comment by jmandel** [comment]
OK. And just to confirm, from the SMART on FHIR installer dir can you run:

    grep  $'\xc2' -r .

to see if the hex valie "0xc2" shows up anywhere?

Also, since the error looks like it's coming at a step where Ansible concatenates a path efrom `host_vars` and `host.name`, can you let us know your hostname and the local path at which the installer is cloned? Any special characters in these names (for example, `Â`)?

**Comment by tse-tamir** [comment]
First i did not find any hex values from the SMART on FHIR installer dir.
The following is the files that stores hots names. You can download it following url: https://github.com/smart-on-fhir/installer
![capture](https://cloud.githubusercontent.com/assets/8093401/14887527/84d9b9f6-0d56-11e6-9603-904f39d8a98b.PNG)

**Comment by jmandel** [comment]
Thanks -- I was trying to inquire about your machine's hostname, and the local path at which you have cloned the git repo (e.g. something like, hostname `morel`, local path `/home/user/hit/smart/installer`)

**Comment by nschwertner** [comment]
Haven't seen this one before. Likely an issue with the hostname on the machine

**Comment by tse-tamir** [comment]
following is my hostname on the machine. is there any issues? 

![capture](https://cloud.githubusercontent.com/assets/8093401/14891455/022e48b2-0d67-11e6-948f-84fd509eedfa.PNG)

**Comment by nschwertner** [comment]
Try putting quotes around the host strings in `custom_settings.yml`. Does it change the behavior in any way?

**Comment by tse-tamir** [comment]
Thanks guys! The reason it didn't work was that the quotes around localhost was written in ASCII which I didn't realize. Now it's working perfectly after fixing that.

sudo ansible-playbook  -c local -i 'localhost,' -vvvv smart-on-fhir-servers.yml
