### ISSUE TITLE
setup fails on TASK [auth-code : patch patient-picker mysql auth install]

### ISSUE THREAD

**Issue by mattStorer** [smart-on-fhir/installer#5]
Hi -

I encountered an error following the instructions for **Building SMART-on-FHIR on fresh Ubuntu 16.04 machine (without Vagrant)** at https://github.com/smart-on-fhir/installer.  The error occurs in _TASK : [auth-code : patch patient-picker mysql auth install]_ with message "Destination directory /home/fhir/apps/static/apps/patient-picker/src/main/resources/db/openidconnect/mysql does not exist".

The folder /home/fhir/apps/static/apps/patient-picker exists, but the src/ subfolder does not.

See screenshot : ![installer-error-patient-picker-no-src](https://cloud.githubusercontent.com/assets/979938/23870519/e53e6570-07e3-11e7-8b25-ba3d9265350f.jpg)

My environment is:
VirtualBox 5.1.14r112924
Ubuntu Linux VM at version 16.04.1-desktop-amd64

Any idea why this error is occurring?  Thanks for any help you can provide!

**Comment by travistcummings** [comment]
Hi,

I've fixed an issue with the path of the .sql file.  Can you update and try it again?

Thanks,
Travis

**Comment by mattStorer** [comment]
resolved!  thanks!
