### ISSUE TITLE
Loading sample apps

### ISSUE THREAD

**Issue by tse-tamir** [smart-on-fhir/installer#5]
I got the following error. 

![untitled](https://cloud.githubusercontent.com/assets/8093401/14912100/58b036c6-0dfa-11e6-94de-db3316ce5d9d.png)

**Comment by jmandel** [comment]
Is this after you made changes to try adding a new sample app as in #6 (or any other changes)?

**Comment by tse-tamir** [comment]
Nope, I got this error when i execute following command from terminal.**sudo ansible-playbook  -c local -i 'localhost,' -vvvv smart-on-fhir-servers.yml **

**Comment by nschwertner** [comment]
I'd guess that something goes wrong with this line:
https://github.com/smart-on-fhir/installer/blob/master/provisioning/roles/common/tasks/sample-data.yml#L162

Are you using Ansible 1.8.2 as prescribed in https://github.com/smart-on-fhir/installer ?

Also, worth noting that we have tested the installer with Ubuntu 14.04 server, not desktop. Especially if you use the Vagrant box that is downloaded by `vagrant up` you will get a very predictable build. Apparently, on a desktop Ubuntu with custom system-wide encoding tools like `cat` and `Ansible` don't behave quite in the same way.

**Comment by tse-tamir** [comment]
I am using Ansible 2.0.2.0 and also using the Ubuntu 14.04 desktop. Let me try what you mentioned.

**Comment by tse-tamir** [comment]
It works!
The reason was the ansible book works only in ubuntu server 14.04. It was not clear for me when i was reading it from documentation :).  
Thanks!

**Comment by nschwertner** [comment]
Thank you. We updated the documentation to reflect your finding: https://github.com/smart-on-fhir/installer/commit/9b1c41988480782a01c92f8b72cfe0bfa7636204
