### ISSUE TITLE
setup fails on TASK [pwm-server : install apache-tomcat]

### ISSUE THREAD

**Issue by mattStorer** [smart-on-fhir/installer#6]
I encountered an error following the instructions for **Building SMART-on-FHIR on fresh Ubuntu 16.04 machine (without Vagrant)** at https://github.com/smart-on-fhir/installer. The error occurs in _TASK : [pwm-server : install apache-tomcat]_ with message "Failure downloading http://mirror.metrocast.net/apache/tomcat/tomcat-8/v8.5.11/bin/apache-tomcat-8.5.11.tar.gz, HTTP Error 404: Not Found".

Digging into this, I see that 8.5.11 doesn't exist, but 8.5.12 does now, so the URL needs to be updated to pull the latest Tomcat at the following URL instead:

http://mirror.metrocast.net/apache/tomcat/tomcat-8/v8.5.12/bin/apache-tomcat-8.5.12.tar.gz

Ideally, the fix would involve some way to identify the latest version that exists before trying to get it, so this sort of problem doesn't occur in the future.

Thanks for your assistance with resolving this!

**Comment by travistcummings** [comment]
Hi, I've added the actual tomcat 8.5.12 artifact to the build now, so it won't pull it from the internet.

**Comment by mattStorer** [comment]
sweet thanks!
