### ISSUE TITLE
default username&pass

### ISSUE THREAD

**Issue by tse-tamir** [smart-on-fhir/installer#7]
I could not find default username&pass to login into the OpenID Connect Server that is installed on my local machine  . Can you please tell me default username&pass?

**Comment by jmandel** [comment]
From https://github.com/smart-on-fhir/installer/blob/master/README.md:

> The authorization server uses the OpenLDAP server running on the virtual machine. The two sample accounts aredemo/demo and admin/password by default. You should change these for production environments. You can connect to the LDAP server on localhost:1389.

Does this work for you?

**Comment by tse-tamir** [comment]
I've already tried this user name and password. It does not work!

Also,the following link is only working on my local machine. http://localhost:9085 for an OAuth2 authorization server

do i need to change something in configuration files if i want to execute a  FHIR API server, SMART apps server, and OpenLDAP  ?

**Comment by nschwertner** [comment]
If the Ansible playbook is failing for you, it is likely that you won't have all the services up. I am guessing that the script never got to deploying LDAP and therefore the Auth server is in "panic" mode. Get through the end of the build before trying.
