### ISSUE TITLE
setup fails on TASK [api-dstu2-sandbox : baseline snapshot]

### ISSUE THREAD

**Issue by mattStorer** [smart-on-fhir/installer#7]
Good afternoon.

I encountered an error following the instructions for **Building SMART-on-FHIR on fresh Ubuntu 16.04 machine (without Vagrant)** at https://github.com/smart-on-fhir/installer. The error occurs in TASK : [api-dstu2-sandbox : baseline snapshot] with message "Status code was not [200]: Connection failure: timed out" for URL http://localhost:8070/api/smartdstu2/sandbox/snapshot/initial.

error screenshot:
![installer-error-api-dstu2-sandbox-baseline-snapshot](https://cloud.githubusercontent.com/assets/979938/24174628/dd57e68a-0e4e-11e7-8a20-9ad51014ea0d.jpg)

below is the response when I attempt to curl http://localhost:8070/api/smartdstu2/sandbox/snapshot/initial, if it helps:
![installer-error-curl-localhost-8070](https://cloud.githubusercontent.com/assets/979938/24174762/a00f9f10-0e4f-11e7-8a38-453679c904e7.jpg)

please let me know if there's any other information you need to assist with resolving this.

thanks for your help!

**Comment by travistcummings** [comment]
This has been fixed.  Thanks!

**Comment by mattStorer** [comment]
ran into this error again...

I got past it once so this isn't a consistent bug.  worst kind I know.  :(

![installer-error-api-dstu2-sandbox-baseline-snapshot-2](https://cloud.githubusercontent.com/assets/979938/24518430/d91a36a6-1536-11e7-89f8-cb6354e3532a.jpg)
