### ISSUE TITLE
setup fails on TASK [auth-code : checkout repository auth_webapp_project]

### ISSUE THREAD

**Issue by mattStorer** [smart-on-fhir/installer#8]
I encountered an error following the instructions for **Building SMART-on-FHIR on fresh Ubuntu 16.04 machine (without Vagrant)** at https://github.com/smart-on-fhir/installer.  The error occurred in _TASK [auth-code : checkout repository auth_webapp_project]_ with message: _"remote: Unauthroized\nfatal: Authentication failed for 'https://bitbucket.org/hspconsortium/reference-auth-server-webapp/"_

It appears that the target repository is locked down and doesn't permit general public access?  Note that I have a BitBucket account, and provided my correct credentials during the install process.  You can also see that this repo is unavailable to me when I'm logged into BitBucket through the web - see screenshots below.

![installer-error-checkout-repo-auth_webapp_project](https://cloud.githubusercontent.com/assets/979938/24430097/d8fb8a8a-13c9-11e7-83e1-e0039af35f94.jpg)
![bitbucket-ref-auth-server-webapp-access-denied](https://cloud.githubusercontent.com/assets/979938/24430100/dbcd8c04-13c9-11e7-9c6e-0f55f379a93d.jpg)

**Comment by travistcummings** [comment]
Hi, this has been fixed.  There were some changes to the HSPC repositories that caused some issues.
